<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Medium_show-password-input</name>
   <tag></tag>
   <elementGuidId>33202985-7528-47ea-9740-d9fc3293f5e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='customer_login']/div[2]/form/p[3]/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.woocommerce-form.woocommerce-form-register.register > p.woocommerce-form-row.woocommerce-form-row--wide.form-row.form-row-wide > span.password-input > span.show-password-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>26229e96-ebbf-4337-892e-5f7cf04b2611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>show-password-input</value>
      <webElementGuid>6e9f5ebd-8bc6-402e-a4c5-8ccf26c367d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_login&quot;)/div[@class=&quot;u-column2 col-2&quot;]/form[@class=&quot;woocommerce-form woocommerce-form-register register&quot;]/p[@class=&quot;woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide&quot;]/span[@class=&quot;password-input&quot;]/span[@class=&quot;show-password-input&quot;]</value>
      <webElementGuid>afe7e41d-7d0c-48d8-bcad-64338b394131</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div[2]/form/p[3]/span/span</value>
      <webElementGuid>d68713ae-f450-44d8-a6bc-3942b8d0bd6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/span/span</value>
      <webElementGuid>a84a335e-f9f2-4c65-8f34-e4ce449627c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
